### ISSUE TITLE
Kunkka Rework [1 skill + 6 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#534]
Ghostship:
1) ship's distance scales with the target point, so the ship is spawned at the appropriate distance behind Kunkka that would cause it to crash at the target point.

Ghostship Scepter:
1) Cast range changes to be the whole travel range (2000).
2) ship's starting position begins at the target point. The ship then travels towards Kunkka (but doesn't necssarily stops at Kunkka's location).

-----------------
TALENTS:
Remove:
-2 Ebb and Flow CD.
+75 torrent damage
+200 torrent radius
+15% tsunami chance
-2 seconds Tidebringer CD.
+7 gold per last hit

Apply:
1. While Kunkka has the rum buff from the Ghostship, Tidebringer has no cooldown.
2. Random secondary torrents appear in random intervals and locations around the main torrent over the secondary torrents duration.
3. Allies being returned to an X mark get a 10% movespeed bonus. Enemies returned get a 10% slow instead. Does not stack (refreshes duration instead)
4. Ghost Ship now drags Kunkka as well to the target location. It does not root him, or affect him in any other way.
5. Enemies affected by Torrent's debuff (either main or secondary) will always be hit by Tidebringer.
6. Add Tsunami to Ebb and Flow's normal cycle, in addition to having the 20% Tsunami chance.

**Comment by Shushishtok** [comment]
Sexy completed by @IamInnocentX3
