### ISSUE TITLE
Lina Rework [3 skills + 5 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#535]
Dragon Slave:
Secondary slaves damage from 35 to 90/100/110/120/140/160/180

Light Strike Array:
Adds 1/1/1/1/2/3/4 explosions. Each explosion adds 6 more rings that explode around the original LSA in a circle after the 0.5 seconds explosion delay. Each explosion after that explodes further away. The amount of explosions increases to cover the circle around it.

Laguna Blade's forked lightning from 1/1/1/2/3/4 targets to 2/2/2/4/6/8 targets.

-----------------
TALENTS:
Remove:
+80 LSA damage
+6 additional LSAs to the sides (not relevant)
-4 Dragon Slave CD
+4%/40 move/attackspeed per Fiery Soul stack
+1 max Fiery soul stacks

Change:
Spawn 2 additional dragon slaves - spawns 4 additional slaves.

Apply:
1. After the secondary dragons finish, spawns an additional main Dragon Slave from the other end of the target point, towards it. This one does not proc the secondary dragons.
2. When a LSA explosion occurs, the previous explosion also occurs, if applicable. (original ring, original ring + first outer ring, first outer ring + second outer ring, second outer ring + third outer ring)
3. Fiery Soul can be activated when having 3 stacks (max)(no target), consuming all Fiery Soul stacks releasing a blast of hot shockwave that deals damage to all enemies in 800 AoE around Lina, dealing up to 450 damage. The closer Lina is to her target, the more damage the blast deals. The blast has a minimum of 100 damage. Has a 5 seconds cooldown each use.
4. Lina's spells cause a DoT on enemies hit, dealing damage every second based on her Fiery Soul stacks at that tick: each stack of Fiery Soul grants a 40 damage bonus (120 max). Having no Fiery Soul stacks doesn't deal damage to enemies on that tick. Lasts 5 seconds. Does not stack with itself, but can be refreshed.
5. Main Light Strike Array's explosion is repeated two times (3 explosions total). Each additional explosion increases its radius by 75, but has its stun times halved (100%, 50%, 25% stun durations).

**Comment by Shushishtok** [comment]
Awwwwwwwwesome
