### ISSUE TITLE
Lion Rework [2 skills + 4 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#536]
Earth Spikes: secondary branches have half the spell's cast range as search radius and half the spike length.

Finger of Death: Frog Panic duration from 0.4/0.4/0.4/0.6/0.8/1 to 1.5/1.5/1.5/1.65/1.8/2 seconds.

--------------------
TALENTS:
Remove:
+70 Earth Spike damage
+150 Chain Hex radius
-3.5 Trigger Finger debuff duration
+300 Frog Panic radius.

Apply:
1. Hexed targets have Break applied to them.
2. Sucking mana with Mana Drain while Lion's mana pool is full makes Lion go into a state of Mana Overcharge. Mana Overcharge lasts 8 seconds from the moment of the first instance that triggered it. It gains stacks equal to mana sucked while Lion has full mana pool. Casting Finger of Death consumes Mana Overcharge's stacks and deals bonus damage equal to the amount of mana sucked.
3. Trigger Finger always triggers, regardless of if Finger killed the target. However, in case the target survived, the mana cost is increased for 15 seconds. Killing the target with Finger of Death resets the duration to 7 seconds.
4. Earth Spikes add a debuff to targets that make them slowed by 25% and take 30% more damage from Finger of Death. The debuff is applied immediately when spikes hit, but its total duration is landing time + 3 seconds.

**Comment by Shushishtok** [comment]
Ohhhhhhhhhh yeah. @IamInnocentX3

**Comment by IamInnocentX3** [comment]
<3
