### ISSUE TITLE
Mangoose Rework [4 skills + 8 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#605]
Shockwave: All Polarized enemies hit by the main shockwave spawn 4 more shockwaves, diagonally, in a form of an X. Mini Shockwaves deal 50% of the main Shockwave's damage, and reach half its length.
Each shockwave grants a Magnetized stack to enemies hit. Each Magnetized stack is depleted every 3 seconds, emitting a Shockwave towards the nearest enemy that deals 25% of the main Shockwave's damage. Continues until no more stacks are left.

Empower: The buff behaves like an aura, which finds enemies in 900 AoE and grants them the Polarized buff causing additional effects from Magnus' spells. Has a 5 seconds duration and refreshes every second, assuming the Empower target is close enough. The debuff is unpurgable, but does not pierce magic immunity.
Supercharge now grants bonus cleave/splash range and radius, along with scaling bonuses.

Supercharge Duration: 20.
Supercharge Move speed bonus: 12/12/12/12/14/16/18%.
Supercharge Attack Speed bonus: 50/50/50/50/75/100/125.
Cleave (melee): starts 150 radius, ends 240. 460 distance. 
Splash (ranged): 240 radius.
Supercharge Cleave (melee): starts 180 radius, ends 320. 620 distance. 
Supercharge Splash (ranged): 360 radius.

Skewer: Always entangles enemies. (since Magnus's targets would always have the Polarized debuff).
Duration scales: 2/2/2/2/2.5/3/3.5 seconds.

Reverse Polarity: All polarized enemies in the entire map are pulled by 300/300/300/400/500/600 units towards Magnus. 
All non-polarized enemy heroes are pulled 500 units towards Magnus.
Non-reverse Polarity slow is removed from this skill.

------------------------------------

TALENTS:
Remove:
+125 RP damage.
+12 Polarize duration.
-11 Skewer CD.
+15% Empower damage.
-4 Shockwave CD.
+5%/50 Supercharge bonuses.
+250 RP pull distance.
+100 RP pull range.

Apply:
1. All Polarized enemies that got pulled towards Magnus' Reverse Polarity but didn't end up in the stun area become 60% slowed for 3 seconds.
2. Shockwaves now always spawn secondary shockwaves halfway through.
3. Skewer causes a mini-RP on cast, gathering all enemy units in 375 radius of Magnus in front of him. Skewer then pushes them forward. 
4. Supercharge grants 30% of the target's main attribute as bonus damage.
5. Shockwaves roots the target briefly for 1 second. Secondary shockwaves root for 0.5 seconds instead.
6. Empower grants 360 degrees Cleave. Has no effect on ranged targets.
7. Polarized enemies are constantly pulled towards their closest ally. The pull strength is 10% of the enemies' movespeed.
8. Ubercharge: Applying Empower on an already Supercharged target makes it Ubercharged (additional modifier on top of Supercharged). Ubercharged makes a target's attacks launch a Mini Shockwave in a straight line. Has an internal cooldown of 1 second. Mini Shockwaves do not split or apply Magnetized stacks, and deal 50% of Shockwave's damage. Ubercharge lasts 8 seconds.

**Comment by IamInnocentX3** [comment]
I'm doing this. 👍

**Comment by Shushishtok** [comment]
Done!
