### ISSUE TITLE
Outworld Devourer Rework [1 skill + 5 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#610]
Change name to Outbalanced Demolisher, for the lulz.

Astral Imprisonment: Prison can be moved while the caster is in it as well. (not sure if it's possible, but it's worth a try)
Prison speed from 100/100/100/100/150/200/250 to 150/200/250/300/325/350/400

-----------------------------------

TALENTS:
Remove:
+200 Astral Imprisonment cast range
+1% Arcane Orb damage
+50% Stolen intelligence from all sources
+2 Arcane Orb int steal
+100 Astral Imprisonment move speed

Apply:
1. Sanity Eclipse cooldown is reduced by 1 second for every intelligence the caster steals while it is off-cooldown.
2. When attacking with Arcane Orb, if Outworld Devourer has more intelligence than its target, the difference in stats explodes in a 300 aoe with pure damage.
3. Astral Imprisonment prison suck up additional enemy units and heroes in its range, removing them from the game for the duration. The suck AoE is equal to the 50 + the caster's intelligence. 
4. Essence Aura's Essence Synergy can proc from enemies as well.
5. Sanity Eclipse landing on heroes that have less than 50% of Outworld Devourer's intelligence suffer double the mana burn (currently 40% x2, so 80%), and causes them to take 50% more damage.

**Comment by Shushishtok** [comment]
Done!
