### ISSUE TITLE
Phantom Assassin Rework [4 skills + 7 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#611]
Stifling Dagger: bonus damage from 65 to 65/80/95/110/110/110.

Phantom Strike: Coup De Grace bonus chance increased from 1/1/1/1/4/7/10% to 3/5/7/9/10/11/12%.

Blur: Revert her to become visible in the map while in the vicinity of an enemy hero (vanilla behavior). She gains normal Blur effect when she's blurry.
As long as she doesn't take damage, her movespeed increases by 1% per second, up to 15%. Taking damage removes the bonus. After 3 seconds where she takes no damage, she regains the bonuses.

Coup De Grace: Die Hard duration increased from 5 to 8.

Scepter effect: additional daggers from 3 to 4.

--------------------------

TALENTS:
Remove:
+30 phantom strike aspd
+35 stifling dagger
+5% bonus crit chance
+1 dagger
+2 phantom strike attacks
+100% coup de grace
+8 coup de grace duration

Apply:
1. Phantom Strike can hit nearby enemies in 300 AoE, dealing a normal attack on them. This attack cannot proc on-hit effects. This effect always occurs on the main target first.
2. Killing an enemy with Coup De Grace's critical grants Phantom Assassin 25 agility bonus for 30 seconds.
3. Blur can be activated to grant Phantom Assassin 100% evasion for 5 seconds. Can be shown visually by making her blurry. Has 22 seconds cooldown.
4. Phantom Strike can be used on yourself. Doing so makes PA rotate around herself, throwing 8 daggers in an omnidirection, in a straight line, up to 1200 range. Each dagger deals 100 damage and causes enemies to bleed, being slowed by 20% and take 50 DoT damage for 4 seconds.
5. Whenever Phantom Assassin evades an attack, she immediately counters, performing a normal attack on her attacker. Can only be done against targets in her attack range. This effect can only occur once every 2 seconds.
6. Phantom Strike causes Phantom Assassin to jump on her main target, slash it once, jump to another target in 500 AoE of it, slash it once and repeat, up to four targets, if found. Phantom always ends up in front of her main target. Each slice always triggers Coup De Grace, but only deals 25% of its value.
7. Phantom Assassin can activate Coup De Grace which increases her base chances by 20% for 3 seconds. However, each of her criticals deal 200% less critical damage. (so instead of 540% crit she'll have 340% crit, which is still a lot). After the duration ends, she cannot crit for 3 seconds. Has 18 seconds cooldown.

**Comment by RodneyMcKay** [comment]
As long as she doesn't take damage, her movespeed increases by 1% per second, up to 15%. Taking damage removes the bonus. After 3 seconds where she takes no damage, she regains the bonuses.

Should add dealing damage also remove the ms bonus.
