### ISSUE TITLE
Shadow Fiend Rework [1 skill + 5 talents + text refactor]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#615]
Requiem of Souls: 
1) Soul Frenzy base duration from 1 to 2 seconds.
2) Soul Frenzy extra duration from 0.2 to 0.3 seconds.

------------------------

TALENTS:
Remove:
+2 Presence armor reduction
-20 Shadowraze mana cost
-3 Shadowraze CD
+10 Necro souls limit
+2 damage from each Necrosoul

Apply:
1. Shadow Razes apply a pool of souls at raze points for 2 seconds, damaging enemies in their AoE for 50 damage per second.
2. Necromastery can be activated to instantly devour souls and heal 80 health per soul. Devours souls until depleted or until Shadow Fiend has full health. Has 12 seconds cooldown.
3. Killing an enemy hero permanenetly increases Necroamastery's soul limit by 1.
4. Enemies affected by Requiem that are hit by Shadowrazes have their debuff fully refreshed.
5. While in Soul Frenzy, Shadowrazes cast points are halved.

------------------------------------------------
TEXT REFACTORING
Shadowraze
Shadow Fiend razes the area in front of him, dealing damage to enemy units in an area.
Mastery of the Darkness: Shadow Fiend masters the shadows at high levels, and can manipulate them to his will.
(close) : Shadowraze gets closer and larger at higher levels
(medium) : Shadowraze forms a semi-circle pattern at higher levels
(far) : Shadowraze forms a line, getting farther every level
Shadow Combo : If all three razes hit within 2.5 seconds, the cooldowns are reset. Can only trigger every 30 seconds.
Soul Raze : Damage increases with each soul that Shadow Fiend possess.

Necromastery
Engorge: Can gain more souls over the limit that lasts 30 seconds each, giving the same benefits as permanent souls. Can only store a percentage of the max souls.
Soul Harvester : Grants 1 soul when attacking or razing an enemy hero.

Presence of the Dark Lord
Shadow Fiend's presence reduces the armor and vision range of nearby enemies.
Creeping Presence : Enemy heroes hit by razes under this aura will have their armor reduced for 7 seconds, which refreshes when another raze hits, up to 3 times.

Requiem of Souls
Shadow Fiend gathers THE MOST TEXT IN ANY VANILLA DOTA 2 ABILITY DESCRIPTION.
Soul Frenzy : After the Requiem ends, Shadow Fiend enters a state of Soul Frenzy, where razes have no cooldown. Lasts for 2 seconds, and is increased by 0.2 seconds for every line that hits an enemy hero. If he misses a raze, Soul Frenzy ends.

**Comment by RodneyMcKay** [comment]
Necromastery can be activated to instantly devour souls and heal 80 health per soul. Devours souls until depleted or until Shadow Fiend has full health. Has 12 seconds cooldown. (i have a little problem with that, sounds terrible if used on panic, but i guess we'll see.)
