### ISSUE TITLE
Sniper Rework [1 skill + 5 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#619]
Take Aim: cooldown from 27/27/27/27/21/15/9 to 16/14/12/11/10/9

---------------------------------------

TALENTS:
Remove:
-2 Aimed Assault CD
+50% Headshot/Perfectshot duration
+80% Perfectshot critical damage
+4 Max Shrapnel charges
+1000 Aimed Assault bonus attack range

Apply:
1. Doubles max Shrapnel charges. Each recharge grants 2 charges.
2. Enemy Units under Shrapnel lose 5 armor and have a 30% chance to miss attacks.
3. Assassination now takes two more seconds to fire. When the cast point is done, Sniper fires a flurry of three Assassination projectiles at the target.
4. Regular Headshots has 20% chance to turn into Perfectshots.
5. Eye Shot: Whenever Sniper fires an Aimed Assault shot, the shot becomes a fatal shot at the target's eye, causing it to bleed heavily and lose vision. Reduces vision of the target by 500, and causes it to take 80 damage per second. Lasts 5 seconds. (purgable)

**Comment by Shushishtok** [comment]
Done!
