### ISSUE TITLE
Ursa Rework [1 skill + 8 talents]

### ISSUE THREAD

**Issue by X-TheDark** [RodneyMcKay/dota_imba#625]
Earthshock:
1) Renamed Hulking Beast to Trembling Steps
2) Earthshock Trembling Steps cooldown from 0.5/0.45/0.4/0.36/0.32/0.28/0.25 to 0.4
3) Earthshock Trembling Steps damage from 20 to 30/60/90/120/140/160/180

Scepter: Effect moved to a talent. Scepter now allows Enrage to be cast while disabled. Doing so does not trigger the cooldown of Enrage!

---------------------------------------

TALENTS:
Remove:
+50% devastsating blow damage
+50% earthshock damage
+3 overpower attacks
+10 fury swipe damage
+100 Enrage spells radius
+1 Overpower disarm duration
+100% skill cooldown rates
-120 seconds Territorial Hunter.

Apply:
1. Trembling Steps' cooldown is improved by 0.01 second for each 10 strength that you have, up to a threshold of 0.2 seconds. 
2. Taking more than 1000 damage in a 3 seconds window causes Ursa to activate Enrage for free.
3. Ursa gets 25% Tenacity when in his Territorial Hunter tree mark radius. Killing an enemy inside Territorial Hunter's AoE resets its cooldown.
4. Devastating Blow damage reduces the target's armor by 2. Lasts 3 seconds, stackable and refreshable.
5. If the target has more than 50% health, Devastating Blow deals 3.5% of the target's maximum health as damage. 
6. Overpower roots enemies in addition to disarming them.
7. Enrage adds 8% of your current health as damage for its duration.
8. Overpower becomes a passive ability. When starting an attack, it procs, granting the attack speed for 4 seconds. This effect no longer counts attacks down and can either have its duration expire or be purged. Overpower goes into cooldown normally when proccing, and cannot be activated again until it is ready again.

**Comment by Shushishtok** [comment]
Done, because I'm sexy and smart.

**Comment by IamInnocentX3** [comment]
O yes u are Thunder Lizard~ :D
